name: Publish to PyPI

on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.release.tag_name }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

    - name: Get version from tag
      run: |
        VERSION=${GITHUB_REF##*/v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build and publish
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        poetry version $VERSION
        poetry build
        poetry publish --no-interaction
